# Generated by Django 2.0.5 on 2018-10-12 13:40

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_pdf_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdf_image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pdf_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pdf_image3',
        ),
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_pdf_path),
        ),
    ]
